version: '3.8'
services:
  postgres_service:
    image: 'postgres:13'
    container_name: postgres_db
    volumes:
      - ./.github/scripts/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_PASSWORD=password

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_service
    depends_on:
      - postgres_service
