server:
  servlet:
    context-path: /api
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/v2_react_spring_demo
      username: postgres
      password: password
      maximum-pool-size: 30